# Generated by Django 3.2.4 on 2021-11-08 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('com', '0003_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='zip',
            new_name='zipcode',
        ),
    ]
