# Generated by Django 3.2.4 on 2021-11-08 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('com', '0004_rename_zip_order_zipcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.CharField(default='card', max_length=200),
            preserve_default=False,
        ),
    ]
