# Generated by Django 3.2.4 on 2021-11-08 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('com', '0005_order_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.CharField(default='1', max_length=200),
            preserve_default=False,
        ),
    ]
